added aws-sso to devcontainer
ministryofjustice/analytical-platform-dashboard pull request #111
Opened 2024-03-20 10:33 UTC by jamesstottmoj

Allows use of aws cli in dev container

2024-03-20 10:43 UTC, michaeljcollinsuk approved these changes
LGTM

2024-04-02 10:43 UTC, michaeljcollinsuk requested changes

2024-04-02 10:43 UTC, michaeljcollinsuk commented on .devcontainer/devcontainer.json
> +    "ghcr.io/ministryofjustice/devcontainer-feature/aws:0": {}
```suggestion
    "ghcr.io/ministryofjustice/devcontainer-feature/aws:0": {},
    "ghcr.io/ministryofjustice/devcontainer-feature/static-analysis:0": {},
```
Adds static analysis, as per @Gary-H9's suggestion

2024-04-02 10:44 UTC, michaeljcollinsuk submitted a review, later dismissed

2024-04-02 10:47 UTC, michaeljcollinsuk commented on .devcontainer/devcontainer.json
> +    "ghcr.io/ministryofjustice/devcontainer-feature/static-analysis:0": {},
```suggestion
    "ghcr.io/ministryofjustice/devcontainer-feature/static-analysis:0": {}
```
Super linter fix

2024-04-02 10:51 UTC, Gary-H9 approved these changes
LGTM

2024-04-02 10:51 UTC, merged